/**
 * Explore City — Pune Edition
 * Authentic Curated Places Database for Pune, Maharashtra, India
 * Coordinates center: 18.5204° N, 73.8567° E
 */

export const PUNE_DEFAULT_CENTER = {
  name: 'Pune, Maharashtra, India',
  lat: 18.5204,
  lng: 73.8567,
  zoom: 13,
};

export const PUNE_CURATED_PLACES = [
  {
    id: 'pune-place-001',
    place_id: 'ChIJ7Yw99rPBwjsR67c3Jv8uG1I',
    name: 'Shaniwar Wada',
    category: 'heritage',
    rating: 4.5,
    user_ratings_total: 48920,
    price_level: '₹',
    address: 'Bajirao Rd, Shaniwar Peth, Pune, Maharashtra 411030',
    lat: 18.5196,
    lng: 73.8553,
    photo_url: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=700',
    opening_hours: '9:30 AM – 5:30 PM Daily (Sound & Light show 7:00 PM)',
    is_open_now: true,
    phone: '+91 20 2445 8011',
    website: 'https://pune.gov.in/tourist-place/shaniwar-wada/',
    tags: ['Peshwa Seat', 'Maratha Empire', 'Delhi Darwaza', 'Historic Fortification'],
    safety_score: 9.4,
    cleanliness_score: 8.8,
    crowd_density: 'busy',
    walkability_score: 9.1,
    accessibility_rating: 8.2,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    notes: 'Historic 1732 seat of the Peshwa rulers of the Maratha Empire. Massive teak gates, courtyards, fountain foundations, and Delhi Darwaza.'
  },
  {
    id: 'pune-place-002',
    place_id: 'ChIJzS1vBfTBwjsRDv5p6d026_w',
    name: 'Aga Khan Palace & Gandhi Memorial',
    category: 'heritage',
    rating: 4.6,
    user_ratings_total: 31200,
    price_level: '₹',
    address: 'Pune-Ahmednagar Rd, Kalyani Nagar, Pune, Maharashtra 411006',
    lat: 18.5524,
    lng: 73.9015,
    photo_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=700',
    opening_hours: '9:00 AM – 5:30 PM Daily',
    is_open_now: true,
    phone: '+91 20 2668 0250',
    website: 'https://asi.nic.in',
    tags: ['Italian Arches', 'Freedom Struggle', 'Gandhi Memorial', 'Lush Gardens'],
    safety_score: 9.8,
    cleanliness_score: 9.5,
    crowd_density: 'moderate',
    walkability_score: 9.4,
    accessibility_rating: 9.0,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    notes: 'Majestic 1892 palace featuring Italian arches and expansive lawns where Mahatma Gandhi and Kasturba Gandhi were interned during the Quit India movement.'
  },
  {
    id: 'pune-place-003',
    place_id: 'ChIJX4u7Y_rBwjsR49QjKov7FzU',
    name: 'Goodluck Cafe & Bakery (Est. 1935)',
    category: 'cafe',
    rating: 4.4,
    user_ratings_total: 24500,
    price_level: '₹',
    address: 'Fergusson College Rd, Deccan Gymkhana, Pune, Maharashtra 411004',
    lat: 18.5173,
    lng: 73.8418,
    photo_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=700',
    opening_hours: '7:30 AM – 11:30 PM Daily',
    is_open_now: true,
    phone: '+91 20 2567 6893',
    website: 'https://cafegoodluck.com',
    tags: ['Irani Cafe', 'Bun Maska', 'Irani Chai', 'FC Road Landmark'],
    safety_score: 9.2,
    cleanliness_score: 8.9,
    crowd_density: 'packed',
    walkability_score: 9.6,
    accessibility_rating: 8.5,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    notes: 'Legendary 1935 heritage Irani cafe at Goodluck Chowk. Celebrated for freshly baked bun maska dipped in steaming special Irani chai and mutton kheema.'
  },
  {
    id: 'pune-place-004',
    place_id: 'ChIJwWv32PjBwjsR7eB7y1jV13w',
    name: 'Vaishali Restaurant & Street Food Corridor',
    category: 'restaurant',
    rating: 4.6,
    user_ratings_total: 41200,
    price_level: '₹₹',
    address: '1218/1, FC Rd, Deccan Gymkhana, Pune, Maharashtra 411004',
    lat: 18.5222,
    lng: 73.8415,
    photo_url: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=700',
    opening_hours: '7:00 AM – 11:00 PM Daily',
    is_open_now: true,
    phone: '+91 20 2553 1244',
    website: 'https://vaishalipune.com',
    tags: ['SPDP', 'Filter Coffee', 'Mysore Masala Dosa', 'FC Road Pulse'],
    safety_score: 9.5,
    cleanliness_score: 9.3,
    crowd_density: 'busy',
    walkability_score: 9.8,
    accessibility_rating: 8.8,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    notes: 'The beating heart of student and cultural life on FC Road. Unmatched Sev Potato Dahi Puri (SPDP), crisp Mysore Sada dosa, and authentic South Indian filter kaapi.'
  },
  {
    id: 'pune-place-005',
    place_id: 'ChIJq7U98PrBwjsR8_d_c3Z48f4',
    name: 'Pataleshwar Cave Temple',
    category: 'heritage',
    rating: 4.6,
    user_ratings_total: 12400,
    price_level: 'Free',
    address: 'Jangali Maharaj Rd, Shivajinagar, Pune, Maharashtra 411005',
    lat: 18.5278,
    lng: 73.8507,
    photo_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700',
    opening_hours: '8:00 AM – 5:30 PM Daily',
    is_open_now: true,
    phone: '+91 20 2553 0833',
    website: 'https://pune.gov.in',
    tags: ['8th-Century Monolithic', 'Rashtrakuta Dynasty', 'Rock-Cut Shrine', 'Basalt Pillars'],
    safety_score: 9.6,
    cleanliness_score: 9.0,
    crowd_density: 'low',
    walkability_score: 9.2,
    accessibility_rating: 8.0,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    notes: 'An 8th-century rock-cut monolithic temple carved directly out of a single basalt rock slab during the Rashtrakuta period, dedicated to Shiva and Nandi.'
  },
  {
    id: 'pune-place-006',
    place_id: 'ChIJk7Q3h_vBwjsRAbU8d_X19fA',
    name: 'The Ritz-Carlton Pune',
    category: 'hotel',
    rating: 4.8,
    user_ratings_total: 3450,
    price_level: '₹₹₹₹',
    address: 'Golf Course Rd, Airport Rd, Yerawada, Pune, Maharashtra 411006',
    lat: 18.5557,
    lng: 73.8967,
    photo_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=700',
    opening_hours: 'Open 24 Hours',
    is_open_now: true,
    phone: '+91 20 6767 5000',
    website: 'https://www.marriott.com/en-us/hotels/pnqrz-the-ritz-carlton-pune/',
    tags: ['Luxury Stay', 'Golf Course Vista', 'Rooftop Lounge', 'Yerawada'],
    safety_score: 9.9,
    cleanliness_score: 9.9,
    crowd_density: 'moderate',
    walkability_score: 8.5,
    accessibility_rating: 9.7,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    notes: 'Ultra-luxury sanctuary featuring skyline terraces overlooking the 100-acre Poona Club Golf Course, Michelin-level dining, and tranquil wellness suites.'
  },
  {
    id: 'pune-place-007',
    place_id: 'ChIJm7Q3n_rBwjsRZb_u_5489fB',
    name: 'Vohuman Cafe & Tea Room',
    category: 'cafe',
    rating: 4.4,
    user_ratings_total: 18900,
    price_level: '₹',
    address: 'Millennium Star, Near Ruby Hall Clinic, Dhole Patil Rd, Pune 411001',
    lat: 18.5309,
    lng: 73.8772,
    photo_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=700',
    opening_hours: '6:00 AM – 7:00 PM Daily',
    is_open_now: true,
    phone: '+91 93734 57574',
    website: 'https://vohumancafe.com',
    tags: ['Cheese Omelette', 'Brun Maska', 'Pune Station Area', 'Vintage Heritage'],
    safety_score: 9.0,
    cleanliness_score: 8.7,
    crowd_density: 'busy',
    walkability_score: 8.9,
    accessibility_rating: 8.4,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    notes: 'Beloved early morning breakfast staple near Pune Station. World famous for double-egg cheese omelettes loaded with butter and crispy brun maska.'
  },
  {
    id: 'pune-place-008',
    place_id: 'ChIJN6z3Q_PBwjsRD4q9VbU1088',
    name: 'Osho Teerth Park & Zen Stream Walkway',
    category: 'attraction',
    rating: 4.6,
    user_ratings_total: 9800,
    price_level: 'Free',
    address: 'Lane 6, Koregaon Park, Pune, Maharashtra 411001',
    lat: 18.5376,
    lng: 73.8942,
    photo_url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=700',
    opening_hours: '6:00 AM – 9:00 AM, 3:00 PM – 6:00 PM Daily',
    is_open_now: true,
    phone: '+91 20 6601 9999',
    website: 'https://osho.com/osho-teerth-park',
    tags: ['Zen Garden', 'Bamboo Groves', 'Ecological Restoration', 'Koregaon Park'],
    safety_score: 9.7,
    cleanliness_score: 9.6,
    crowd_density: 'low',
    walkability_score: 9.8,
    accessibility_rating: 8.9,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    notes: 'A celebrated 12-acre environmental project transforming a barren municipal nala into an exquisite Japanese-style Zen garden with bamboo arches, wooden bridges, and running water.'
  },
  {
    id: 'pune-place-009',
    place_id: 'ChIJ4zY7j_rBwjsRV_4jK218088',
    name: 'Bedekar Tea Stall & Puneri Misal (Est. 1948)',
    category: 'restaurant',
    rating: 4.3,
    user_ratings_total: 16700,
    price_level: '₹',
    address: '418, Munjabacha Bol, Narayan Peth, Pune, Maharashtra 411030',
    lat: 18.5152,
    lng: 73.8519,
    photo_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=700',
    opening_hours: '7:30 AM – 7:00 PM (Closed Mon)',
    is_open_now: true,
    phone: '+91 20 2445 1076',
    website: 'https://bedekarteastall.in',
    tags: ['Puneri Misal', 'Historic Peth Area', 'Authentic Kat & Rassa', 'Narayan Peth'],
    safety_score: 9.1,
    cleanliness_score: 8.8,
    crowd_density: 'busy',
    walkability_score: 9.3,
    accessibility_rating: 8.0,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    notes: 'The definitive temple of authentic Puneri sweet-and-spicy Misal with homemade poha, farsan, and simmering spicy kat broth. Served in the heritage heart of Old Pune.'
  },
  {
    id: 'pune-place-010',
    place_id: 'ChIJb7c9k_rBwjsRF_8b_5289fE',
    name: 'Kayani Bakery (Est. 1955)',
    category: 'cafe',
    rating: 4.5,
    user_ratings_total: 22100,
    price_level: '₹₹',
    address: '6, Dr Coyaji Rd, Hulshur, Camp, Pune, Maharashtra 411001',
    lat: 18.5147,
    lng: 73.8814,
    photo_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=700',
    opening_hours: '7:30 AM – 1:00 PM, 3:30 PM – 8:00 PM (Closed Sun)',
    is_open_now: true,
    phone: '+91 20 2613 2983',
    website: 'https://kayanibakery.com',
    tags: ['Mawa Cake', 'Shrewsbury Biscuits', 'Pune Camp Heritage', 'Parsi Bakery'],
    safety_score: 9.3,
    cleanliness_score: 9.2,
    crowd_density: 'busy',
    walkability_score: 9.4,
    accessibility_rating: 8.7,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 220).toISOString(),
    notes: 'Historic Parsi bakery famed across India for its warm Mawa cakes and melt-in-mouth buttery Shrewsbury biscuits. Lines form outside before morning batch opening.'
  },
  {
    id: 'pune-place-011',
    place_id: 'ChIJc8d9m_rBwjsRG_9c_5389fF',
    name: 'Raja Dinkar Kelkar Museum',
    category: 'heritage',
    rating: 4.6,
    user_ratings_total: 11500,
    price_level: '₹₹',
    address: 'No. 1377/78, Kamal Kunj, Bajirao Rd, Shukrawar Peth, Pune 411002',
    lat: 18.5108,
    lng: 73.8550,
    photo_url: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?w=700',
    opening_hours: '10:00 AM – 5:30 PM Daily',
    is_open_now: true,
    phone: '+91 20 2448 2101',
    website: 'https://rajakelkarmuseum.org',
    tags: ['Mastani Mahal', 'Indian Musical Instruments', '18th Century Antiques', 'Peths'],
    safety_score: 9.5,
    cleanliness_score: 9.2,
    crowd_density: 'moderate',
    walkability_score: 9.0,
    accessibility_rating: 8.3,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    notes: 'A collection of over 20,000 rare artifacts assembled by Dr. D.G. Kelkar, showcasing carved doorways, betel nut cutters, musical instruments, and a recreation of Mastani Mahal.'
  },
  {
    id: 'pune-place-012',
    place_id: 'ChIJd9e9o_rBwjsRH_0d_5489fG',
    name: 'Conrad Pune (Luxury & Dining)',
    category: 'hotel',
    rating: 4.7,
    user_ratings_total: 7800,
    price_level: '₹₹₹₹',
    address: '7, Mangaldas Rd, Sangamvadi, Pune, Maharashtra 411001',
    lat: 18.5358,
    lng: 73.8827,
    photo_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=700',
    opening_hours: 'Open 24 Hours',
    is_open_now: true,
    phone: '+91 20 6745 6745',
    website: 'https://www.hilton.com/en/hotels/pnqpcci-conrad-pune/',
    tags: ['Hilton Luxury', 'Art Deco', 'Koji Pan-Asian', 'Central Pune'],
    safety_score: 9.8,
    cleanliness_score: 9.8,
    crowd_density: 'moderate',
    walkability_score: 9.1,
    accessibility_rating: 9.6,
    data_source: 'demo_fallback',
    sourced_at: new Date(Date.now() - 1000 * 60 * 260).toISOString(),
    notes: 'Luxury hotel located in the heart of the central business and cultural district, renowned for Art Deco architecture and gourmet culinary destinations.'
  }
];
